Return status 1 and do not output blank lines when fetching config keys that don't exist

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -10,10 +10,12 @@
 #
 # <ul id="toc" style="display:none;"></ul>
 VERSION=1.0.1
+
 COLORS=
 COLOR_BOLD=1
 COLOR_RED=31
 COLOR_YELLOW=33
+
 DEFAULT_CONFIG=./deploy.conf
 DEFAULT_UPDATE_REPO=git://github.com/AlphaHydrae/deploy.git
 
@@ -769,7 +771,8 @@ config() {
   #   root
   #   ```
   else
-    get_last_config_key_value $1
+    local value=$(get_last_config_key_value $1)
+    test -n "$value" && echo "$value"
   fi
 }
 
@@ -785,7 +788,12 @@ config() {
 # ```
 config_all() {
   require_env
-  get_all_config_key_values "$1"
+
+  local key="$1"
+  test -n "$key" || abort "<key> missing"
+
+  local values=$(get_all_config_key_values "$key")
+  test -n "$values" && echo "$values"
 }
 
 # ### `<env> console [path]`
