Document most of the source

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -5,6 +5,8 @@
 # * **Source:** https://github.com/AlphaHydrae/deploy
 # * **Originally by:** https://github.com/visionmedia/deploy
 
+VERSION="1.0.1"
+
 
 
 
@@ -53,11 +55,13 @@ EOF
 #
 # Perform first-time setup tasks before deployment.
 setup() {
+  require_env
+
   local path="$(get_last_config_value path)"
   local repo="$(get_last_config_value repo)"
 
   # Run user-defined `pre-setup` hooks (if any).
-  hooks pre-setup "$path"
+  run_hooks pre-setup "$path"
 
   # Create the `releases` and `tmp` directories in the deployment directory
   # if they don't already exist.
@@ -74,7 +78,7 @@ setup() {
     || abort "failed to clone repo"
 
   # Run user-defined `post-setup` hooks (if any).
-  hooks post-setup "$path"
+  run_hooks post-setup "$path"
 
   log setup complete
 }
@@ -83,6 +87,9 @@ setup() {
 #
 # Deploys the latest changes from the repository.
 deploy_ref() {
+  require_env
+  require_no_local_changes
+
   local path=`get_last_config_value path`
   local release=`date -u '+%Y-%m-%d-%H-%M-%S'`
   local current_dir="$path/current"
@@ -99,7 +106,7 @@ deploy_ref() {
   echo "    release: $release"
 
   # Run user-defined pre-deploy hooks (if any).
-  hooks pre-deploy $current_dir
+  run_hooks pre-deploy $current_dir
 
   # Fetch the latest changes from the repository (from the specified ref).
   log fetching updates
@@ -118,7 +125,7 @@ deploy_ref() {
     || abort "could not extract source from repository"
 
   # Run user-defined deploy hooks (if any).
-  hooks deploy $release_dir
+  run_hooks deploy $release_dir
 
   # Link the `current` directory to the new release.
   log linking current
@@ -126,7 +133,7 @@ deploy_ref() {
     || abort "could not create current symlink"
 
   # Run user-defined post-deploy hooks (if any).
-  hooks post-deploy $current_dir
+  run_hooks post-deploy $current_dir
 
   log successfully deployed
 }
@@ -202,6 +209,7 @@ config() {
 # #=> root
 # ```
 config_all() {
+  require_env
   get_all_config_values "$1"
 }
 
@@ -209,6 +217,7 @@ config_all() {
 #
 # Launches an interactive ssh console session.
 console() {
+  require_env
 
   # If an **absolute path** is given, the session starts there.
   local path="$1"
@@ -229,6 +238,97 @@ console() {
   $shell -t "cd $path; \$SHELL -il"
 }
 
+# ### `<env> exec <cmd>`
+#
+# Executes the specified command on the host.
+#
+# ```sh
+# deploy production exec ps -ef
+# ```
+exec_remote_command() {
+  require_env
+  local path="$(get_last_config_value path)"
+  run "cd $path && $(build_export_env_command) && $@"
+}
+
+# ### `<env> list`
+#
+# Lists the releases that have been deployed on the host.
+#
+# ```sh
+# $> deploy production list
+# 2016-12-24-17-45-23
+# 2017-01-01-02-03-43
+# 2017-04-01-00-00-00
+# ```
+list_releases() {
+  require_env
+  local path=`get_last_config_value path`
+  run "ls -1 $path/releases"
+}
+
+# ### `update [--prefix dir] [--path path] [ref]`
+#
+# Updates this script to the latest version by downloading it from the Git repository.
+update_self() {
+  local ref=
+  local path=
+  local prefix=/usr/local
+
+  # This sub-command requires additional shell commands to be available.
+  require_command chmod cp mktemp
+
+  while test $# -ne 0; do
+    arg=$1; shift
+    case $arg in
+      # If a `--prefix` directory is specified, the script will be installed
+      # at `bin/deploy` relative to that directory.
+      --prefix) prefix="$1"; shift ;;
+      # If a `--path` file is specified, the script will be installed there
+      # (this overrides the `--prefix` option).
+      --path) path="$1"; shift ;;
+      # The first optional argument is the Git revision from which to download the script.
+      # This defaults to `master`.
+      *)
+        if test -z "$ref"; then
+          ref="$arg"
+        else
+          abort "unknown command or option $arg"
+        fi
+        ;;
+    esac
+  done
+
+  test -z "$path" && path=$prefix/bin/deploy
+
+  # The installation path must be a writable file or not exist.
+  test -e "$path" && ! test -f "$path" && abort "$path already exists and is not a file"
+  test -f "$path" && ! test -w "$path" && abort "$path is not writable"
+
+  # If the installation path does not already exist, its parent must be a writable directory.
+  local dir="$(dirname "$path")"
+  test -f "$path" || test -e "$dir" || abort "$dir does not exist"
+  test -f "$path" || test -d "$dir" || abort "$dir is not a directory"
+  test -f "$path" || test -w "$path" || abort "$dir is not writable"
+
+  test -z "$ref" && ref=master
+  log "updating deploy from $ref @ $DEPLOY_UPDATE_REPO"
+
+  # The Git repository is downloaded in a temporary directory that will be cleaned up when the update is done (or fails).
+  local tmp_dir=`mktemp -d -t deploy`
+  trap "cleanup $tmp_dir" EXIT
+
+  # Once the Git directory is cloned, the correct revision of the script is copied to the installation path and made executable.
+  cd "$tmp_dir" \
+    && git clone $DEPLOY_UPDATE_REPO "$tmp_dir" || abort could not clone $DEPLOY_UPDATE_REPO \
+    && { git rev-parse --verify $ref &>/dev/null && git reset --hard $ref || { git fetch origin $ref && git reset --hard origin/$ref; }; } || abort could not find $ref \
+    && cp bin/deploy $path \
+    && chmod +x /usr/local/bin/deploy \
+    || abort could not update deploy
+
+  log "updated $VERSION -> `./bin/deploy --version`"
+}
+
 
 
 
@@ -240,10 +340,13 @@ console() {
 # `./deploy.conf` is used as the configuration file by default.
 # Use this option or the `$DEPLOY_CONFIG` environment variable to load a different file.
 #
-# The option takes precedence over the environment variable.
+# The command line option takes precedence over the environment variable.
 set_config_path() {
-  test -f "$1" || abort "invalid --config <path> (no such file)"
-  DEPLOY_CONFIG="$1"
+  local file="$1"
+  test -e "$file" || abort "invalid config file: $file does not exist"
+  test -f "$file" || abort "invalid config file: $file is not a file"
+  test -r "$file" || abort "invalid config file: $file cannot be read"
+  DEPLOY_CONFIG="$file"
 }
 
 # ### `--version`
@@ -391,7 +494,7 @@ get_config_values_recursive() {
   local values=
 
   if ! config_section_exists $env; then
-    echo_color $COLOR_RED "    [$env] config section not defined" 1>&2
+    log_error "    [$env] config section not defined"
     exit 0
   fi
 
@@ -488,30 +591,204 @@ get_config_section() {
     | sed "/^\[/d"
 }
 
+# ### `hooks $name $host_cwd`
+#
+# Executes all user-defined hooks of the specified name in the current environment.
+run_hooks() {
+
+  local name=$1
+  test -n "$name" || abort hook name required
+
+  # The command are run in the specified working directory on the host.
+  local dir=$2
+  test -n "$dir" || abort hook working directory required
+
+  local path=`get_last_config_value path`
+  local commands=`get_all_config_values $name`
+
+  log hook $name
+
+  # Nothing is done if no hooks are defined.
+  if test -z "$commands"; then
+    echo "    nothing to do"
+    return 0
+  fi
+
+  local old_ifs=$IFS
+  IFS=$'\n'
+
+  for cmd in $(echo "$commands"); do
+    IFS="$old_ifs"
+
+    # Various environment variables are exported before executing each hook,
+    # `$DEPLOY_PATH` indicating the deployment directory (not necessarily the same
+    # as the hook working directory), and any additional user-defined variables.
+    # See `build_export_env_command`.
+    run "cd $dir \
+         && $(build_export_env_command) \
+         && $cmd 2>&1" \
+      || abort $name hook failed
+
+    IFS=$'\n'
+  done
+
+  IFS="$old_ifs"
+}
+
 # ### `build_ssh_command`
 #
 # Builds an SSH command to connect to the host.
 build_ssh_command() {
+  # Various SSH options can be given through the config file or environment variables.
+  # The `host` config (or `$DEPLOY_HOST` variable) is the only mandatory one.
   local host=$(get_last_config_value host)
   test -n "$host" || abort "no host config found in environment $DEPLOY_ENV"
 
   local url=$host
 
+  # Specify the user to connect to the host as with the `user` config or the `$DEPLOY_USER` variable.
   local user=$(get_last_config_value user)
-  if test -n "$user"; then
-    url="$user@$url"
-  fi
+  test -n "$user" && url="$user@$url"
 
+  # Supply a private key (identity file) with the `key` config or the `$DEPLOY_KEY` variable.
   local key="`get_last_config_value key`"
-  local forward_agent="`get_last_config_value forward-agent`"
-  local port="`get_last_config_value port`"
-  local needs_tty="`get_last_config_value needs_tty`"
+  test -n "$key" && key="-i $key"
 
-  test -n "$forward_agent" && local agent="-A"
-  test -n "$key" && local identity="-i $key"
-  test -n "$port" && local port="-p $port"
-  test -n "$needs_tty" && local tty="-t"
-  echo "ssh $tty $agent $port $identity $url"
+  # Enable agent forwarding with the `forward-agent` config or the `$DEPLOY_FORWARD_AGENT` variable.
+  local forward_agent="`get_last_config_value forward-agent`"
+  test -n "$forward_agent" && forward_agent="-A"
+
+  # Specify the host port to connect to with the `port` config or the `$DEPLOY_PORT` variable.
+  local port="`get_last_config_value port`"
+  test -n "$port" && port="-p $port"
+
+  # Force pseudo-terminal allocation with the `tty` key or the `$DEPLOY_TTY` variable.
+  local tty="`get_last_config_value tty`"
+  test -n "$tty" && tty="-t"
+
+  echo "ssh $tty $forward_agent $port $key $url"
+}
+
+# ### `run $@`
+#
+# Runs the specified command on the host through SSH.
+run() {
+  local shell="`build_ssh_command`"
+  echo_command "$@"
+  $shell $@
+}
+
+# ### `build_export_env_command`
+#
+# Returns a command to run on the host to export environment variables for further command execution.
+build_export_env_command() {
+
+  # The `$DEPLOY_PATH` variable is always exported and indicates the deployment directory
+  # configured by the user with the `path` config or the local `$DEPLOY_PATH` variable.
+  local path="$(get_last_config_value path)";
+  local env_command="export DEPLOY_PATH=$path"
+
+  # Additional variables may be exported by the user with the `env` config in the form `env FOO=BAR`.
+  env_command="$command $(echo `get_all_config_values env`|sed 's/\n/ /g')"
+
+  # Local variables may also be exported on the host with the `forward-env` config in the form `forward-env BAZ`.
+  for forward_env in $(echo `get_all_config_values forward-env`|sed 's/\n/ /g'); do
+    env_command="$env_command $forward_env=$(echo "${!forward_env}"|sed 's/ /\\ /g')"
+  done
+
+  echo "$env_command"
+}
+
+# ### `require_env`
+#
+# Ensures that an environment has been selected by providing an argument before the command to run.
+# This is required for most (but not all) sub-commands. See `main`.
+require_env() {
+  test -n "$DEPLOY_ENV" || abort "<env> required"
+  # It also ensures that the config file contains a section for that environment.
+  config_section_exists $DEPLOY_ENV || abort "[$DEPLOY_ENV] config section not defined"
+}
+
+# ### `require_no_local_changes`
+#
+# Ensures that all changes are committed and pushed before deploying.
+require_no_local_changes() {
+  git --no-pager diff --exit-code --quiet || abort "commit or stash your changes before deploying"
+  git --no-pager diff --exit-code --quiet --cached || abort "commit your staged changes before deploying"
+  [ -z "`git rev-list @{upstream}.. -n 1`" ] || abort "push your changes before deploying"
+}
+
+# ### `command_exists $command`
+#
+# Checks whether the specified command exists.
+command_exists() {
+  command -v "$1" >/dev/null 2>&1
+}
+
+# ### `require_command $command`
+#
+# Ensures that the specified command exists.
+require_command() {
+  command_exists "$1" || abort "$1 command not found"
+}
+
+# ### `check_requirements`
+#
+# Ensures that all commands required for the execution of this script exist.
+# Some optional commands are not checked here. See `update_self`.
+check_requirements() {
+  for com in cat cut date git grep ls mkdir sed ssh tail tar; do
+    require_command $com
+  done
+}
+
+# ### `make_temporary_directory`
+#
+# Creates a temporary directory that will be cleaned up when this script exits.
+make_temporary_directory() {
+  DEPLOY_TMP_DIR="$(mktemp -d -t deploy)"
+  echo "$DEPLOY_TMP_DIR"
+}
+
+# ### `cleanup [$dir]`
+#
+# Removes the specified directory if an argument is specified and it is an existing directory.
+cleanup() {
+  local tmp_dir="$1"
+  test -n "$tmp_dir" && test -d "$tmp_dir" && rm -fr "$tmp_dir"
+}
+
+# ### `abort $message`
+#
+# Aborts execution of this script with the specified message.
+# The script exists with status code 1.
+abort() {
+  echo
+  log_error "  $@"
+  echo
+  exit 1
+}
+
+# ### `log $message`
+#
+# Logs a deployment progress message.
+log() {
+  echo
+  echo_color $COLOR_BOLD "  ○ $@"
+}
+
+# ### `log_command $message`
+#
+# Logs a command that is being executed on the host.
+log_command() {
+  echo_color $COLOR_YELLOW "$@" | tr -s ' ' | sed 's/^/    /'
+}
+
+# ### `log_error $message`
+#
+# Logs an error.
+log_error() {
+  echo_color $COLOR_RED "$@" 1>&2
 }
 
 # ### `echo_color $color $message`
@@ -524,168 +801,50 @@ echo_color() {
   echo -e "\033[${color}m${message}\033[0m"
 }
 
-# ### `run $@`
-#
-# Runs the specified command on the host through SSH.
-run() {
-  local shell="`build_ssh_command`"
-  echo_color 33 "$@" | tr -s ' ' | sed 's/^/    /'
-  $shell $@
-}
+# ## Main command
+COLOR_BOLD=1
+COLOR_RED=31
+COLOR_YELLOW=33
 
-# Returns the command used to export the user's environment
-env_command() {
-  local path=`get_last_config_value path`
-  echo "export ROOT_DIR=$path $(env_variables)"
-}
+# Exit immediately if requirements are not met.
+check_requirements
 
-env_variables() {
-  local env="$(echo `get_all_config_values env`|sed 's/\n/ /g')"
+# If an `.env` file is present in the current directory, it is sourced before running any commands.
+test -f .env && { test -r .env || abort "environment file .env is not readable"; }
+test -f .env && { . .env || abort "an error occurred while sourcing .env"; }
 
-  for forward_env in $(echo `get_all_config_values forward-env`|sed 's/\n/ /g'); do
-    env="$env $forward_env=$(echo "${!forward_env}"|sed 's/ /\\ /g')"
-  done
+DEPLOY_ENV=
 
-  echo "$env"
-}
+# The configuration file defaults to `./deploy.conf`.
+test -z "$DEPLOY_CONFIG" && DEPLOY_CONFIG=./deploy.conf
 
-# Execute hook(s) <name> relative to the path configured
-hooks() {
+# The repo to update the script from defaults to `git://github.com/AlphaHydrae/deploy.git`.
+test -z "$DEPLOY_UPDATE_REPO" && DEPLOY_UPDATE_REPO=git://github.com/AlphaHydrae/deploy.git
 
-  local hook=$1
-  test -n "$hook" || abort hook name required
+while test $# -ne 0; do
+  arg=$1; shift
+  case $arg in
+    -h|--help) usage; exit ;;
+    -V|--version) version; exit ;;
+    -c|--config) set_config_path $1; shift ;;
+    -C|--chdir) log cd $1; cd $1; shift ;;
+    exec) exec_remote_command $@; exit ;;
+    console) console $1; exit ;;
+    setup) setup $@; exit ;;
+    list) list_releases; exit ;;
+    ref) deploy_ref $1; exit ;;
+    update) update_self $@; exit ;;
+    config) config $@; exit ;;
+    config-all) config_all $@; exit ;;
+    *)
+      if test -z "$DEPLOY_ENV"; then
+        DEPLOY_ENV=$arg;
+      else
+        abort "unknown command or option $arg"
+      fi
+      ;;
+  esac
+done
 
-  local dir=$2
-  test -n "$dir" || abort working directory required
-
-  local path=`get_last_config_value path`
-  local commands=`get_all_config_values $hook`
-
-  log hook $hook
-
-  if test -n "$commands"; then
-    local old_ifs=$IFS
-    IFS=$'\n'
-
-    for cmd in $(echo "$commands"); do
-      IFS="$old_ifs"
-
-      run "cd $dir \
-           && export ROOT_DIR=$path $(env_variables) \
-           && $cmd 2>&1" \
-        || abort $hook hook failed
-
-      IFS=$'\n'
-    done
-
-    IFS="$old_ifs"
-  else
-    echo "    nothing to do"
-  fi
-}
-
-# List deploys
-list_deploys() {
-  local path=`get_last_config_value path`
-  run "ls -1 $path/releases"
-}
-
-# Require environment arg
-require_env() {
-  test -z "$DEPLOY_ENV" && abort "<env> required"
-  config_section_exists $DEPLOY_ENV || abort "[$DEPLOY_ENV] config section not defined"
-}
-
-# Ensure all changes are committed and pushed before deploying
-check_for_local_changes() {
-  git --no-pager diff --exit-code --quiet || abort "commit or stash your changes before deploying"
-  git --no-pager diff --exit-code --quiet --cached || abort "commit your staged changes before deploying"
-  [ -z "`git rev-list @{upstream}.. -n 1`" ] || abort "push your changes before deploying"
-}
-
-deploy_tmp() {
-  DEPLOY_TMP_DIR="$(mktemp -d -t deploy)"
-  echo "$DEPLOY_TMP_DIR"
-}
-
-update() {
-  log "updating deploy from $UPDATE_REPO"
-
-  local tmp_dir=`deploy_tmp`
-  cd "$tmp_dir" \
-    && git clone $UPDATE_REPO "$tmp_dir" \
-    && make install \
-    || abort could not update deploy
-
-  log "updated $VERSION -> `./bin/deploy --version`"
-}
-
-# Abort with <msg>
-abort() {
-  echo
-  echo_color $COLOR_RED "  $@" 1>&2
-  echo
-  exit 1
-}
-
-cleanup() {
-  test -n "$DEPLOY_TMP_DIR" && test -d "$DEPLOY_TMP_DIR" && rm -fr "$DEPLOY_TMP_DIR"
-}
-
-# Log <msg>
-log() {
-  echo
-  echo_color $COLOR_BOLD "  ○ $@"
-}
-
-main() {
-  trap cleanup EXIT
-
-  # Source environment file if present
-  [ -f .env ] && . .env
-
-  COLOR_BOLD=1
-  COLOR_RED=31
-  COLOR_YELLOW=33
-
-  VERSION="1.0.1"
-  DEPLOY_ENV=
-
-  UPDATE_REPO=git://github.com/AlphaHydrae/deploy.git
-  DEPLOY_TMP_DIR=
-
-  if test -z "$DEPLOY_CONFIG"; then
-    DEPLOY_CONFIG=./deploy.conf
-  fi
-
-  # Parse arguments
-  while test $# -ne 0; do
-    arg=$1; shift
-    case $arg in
-      -h|--help) usage; exit ;;
-      -V|--version) version; exit ;;
-      -c|--config) set_config_path $1; shift ;;
-      -C|--chdir) log cd $1; cd $1; shift ;;
-      exec) require_env; run "cd `get_last_config_value path`/current && $(env_command) && $@"; exit ;;
-      console) require_env; console $1; exit ;;
-      setup) require_env; setup $@; exit ;;
-      list) require_env; list_deploys; exit ;;
-      ref) require_env; check_for_local_changes; deploy_ref $1; exit ;;
-      update) update; exit ;;
-      config) config $@; exit ;;
-      config-all) require_env; config_all $@; exit;;
-      *)
-        if test -z "$DEPLOY_ENV"; then
-          DEPLOY_ENV=$arg;
-        else
-          abort "unknown command or option $arg"
-        fi
-        ;;
-    esac
-  done
-
-  usage
-  abort "no command given"
-}
-
-main "$@"
+usage
+abort "no command given"
